### ISSUE TITLE
permissions denied

### ISSUE THREAD

**Issue by Zwilla** [btccom/btc_pool_docs#1]
https://eu-pool.api.btc.com/v1/account/info?access_key=My_access_key,puid=My_pubid

respond:
{"err_no":20001,"err_msg":"permissions denied"}

https://${Endpoint}/${Version}/${Path}? -> ???????

**Comment by dubuqingfeng** [comment]
The puid needs Belong to the Europe, if you use "https://eu-pool.api.btc.com".
And you can use "https://pool.api.btc.com" now.

**Comment by dubuqingfeng** [comment]
![image](https://user-images.githubusercontent.com/6101854/47772233-f261fc80-dd20-11e8-8862-a05b3d2fd119.png)

**Comment by Zwilla** [comment]
This is working!
https://eu-pool.api.btc.com/v1/account/info?puid=My_pubid&access_key=My_access_key
And this also!
https://pool.api.btc.com/v1/account/info?puid=My_pubid&access_key=My_access_key

Thx!

Can you change the documents to not confusing others? THX
